hostname core2
password zebra
!
router ospf
 ospf router-id 10.0.8.2
 ! Connect to DMZ
 network 10.0.8.0/24 area 0
 ! Connect to Dist 1 and 2
 network 10.0.6.0/24 area 0
 network 10.0.7.0/24 area 0
!
line vty
!
