hostname dist1
password zebra
!
router ospf
 ospf router-id 10.0.2.2
 ! Upstream to core1 and core2 in Area 0
 network 10.0.2.0/24 area 0
 network 10.0.6.0/24 area 0
 ! Downstream to Access 1 in Area 1
 network 10.0.4.0/24 area 1
 ! Security: Don't send OSPF Hello packets to end hosts
 passive-interface dist1-eth1
!
line vty
!
