hostname dist2
password zebra
!
router ospf
 ospf router-id 10.0.3.2
 ! Upstream to core1 and core2 in Area 0
 network 10.0.3.0/24 area 0
 network 10.0.7.0/24 area 0
 ! Downstream to Access 2 in Area 2
 network 10.0.5.0/24 area 2
 ! Security: Don't send OSPF Hello packets to end hosts
 passive-interface dist2-eth1
!
line vty
!
