hostname dmz_r
password zebra
!
router ospf
 ospf router-id 192.168.100.254
 network 10.0.1.0/24 area 0
 network 10.0.8.0/24 area 0
 network 192.168.100.0/24 area 0
 default-information originate always
 ! Security: Don't send OSPF Hello packets to DMZ servers
 passive-interface dmz_r-eth0
 passive-interface dmz_r-eth3
!
line vty
!
